

const data = [
    {
        "index": 1,
        "Timestamp": 45026.81066221065,
        "second_email": "sourav_phd22@iiitkalyani.ac.in",
        "name": "Sourav Karmakar",
        "Student ID ": "PhD/21015/821",
        "email": "sourav_phd22@iiitkalyani.ac.in",
        "session": '2022',
        "supervisor": "Dr. Rinky Sha",
        "research_area": "Bio and Chemical Sensors",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://orcid.org/0000-0003-2825-1234",
        "img": "https://drive.google.com/open?id=1Y0lfdkwntc44qTT7iEV4QgdS9LAFw2aT",
    },
    {
        "index": 2,
        "Timestamp": 45026.84211677083,
        "second_email": "shuklamondal.cse@gmail.com",
        "name": "Shukla Mondal",
        "Student ID ": "PhD/21007/655",
        "email": "shukla_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. SK Hafizul Islam, Dr. Arup Kumar Pal",
        "research_area": "Secure Content-Based Image Retrieval",
        "status": "Ongoing",
        "type": "External",
        "fellowship": "",
        "institute": "Indian Institute of Technology (Indian School of Mines) Dhanbad",
        "links": "https://sites.google.com/view/shuklamondal",
        "img": "/phd/ShuklaMondal.webp",
    },
    {
        "index": 3,
        "Timestamp": 45026.98533681713,
        "second_email": "nirban_phd22@iiitkalyani.ac.in",
        "name": "Nirban Kumar Saha",
        "Student ID ": "PhD/22003/850",
        "email": "nirban_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Dalia Nandi",
        "research_area": "Internet of Things",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Institute of Engineering & Management, Kolkata",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?hl=en&view_op=list_works&authuser=1&gmla=ABEO0YpoAtcstkCCA63_cAkZwVdpfRq0alRcWLmreb1dWEm5AHZsA9D9hXHzVJBZI7mzgw9KbfzSveTEDOkveA&user=-FAQnC4AAAAJ",
        "img": "/phd/NirbanKumarSaha.webp",
    },
    {
        "index": 5,
        "Timestamp": 45027.45129131945,
        "second_email": "subhajitdebnath007@gmail.com",
        "name": "Subhajit Debnath",
        "Student ID ": "Ph.D/Science/18022/0000426",
        "email": "subhajitd@iiitkalyani.ac.in",
        "session": "2019",
        "supervisor": "Dr. Uma Das",
        "research_area": "Atmospheric Physics ",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://orcid.org/0000-0001-5088-0382",
        "img": "/phd/subhajitDebnath.webp"
    },
    {
        "index": 6,
        "Timestamp": 45027.51017081019,
        "second_email": "abhishekrajibghosh@gmail.com",
        "name": "Abhishek Ghosh",
        "Student ID ": "PhD/22008/1020",
        "email": "abhishek_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Pratik Chakraborty",
        "research_area": "Wireless Communication",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://scholar.google.com/citations?user=SpKQtZsAAAAJ&hl=en",
        "img": "/phd/Abishekgosh.webp"
    },
    {
        "index": 7,
        "Timestamp": 45027.51045872685,
        "second_email": "786sabnur@gmail.com",
        "name": "Sabnur Rahaman",
        "Student ID ": "PhD/22010/1022",
        "email": "sabnur_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. SK Hafizul Islam",
        "research_area": "Cryptography and Information Security",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Net Fellowship)",
        "img": "/phd/SabnurRahaman.webp"
    },
    {
        "index": 8,
        "Timestamp": 45027.51705224537,
        "second_email": "debarpita123456@gmail.com",
        "name": "Debarpita Paul",
        "Student ID ": "PhD/22009/1021",
        "email": "debarpita_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Dalia Nandi",
        "research_area": "Channel modelling for wireless communication",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "img": "/phd/DebarpitaPaul.webp"
    },
    {
        "index": 9,
        "Timestamp": 45027.517597060185,
        "second_email": "sahadebmani94@gmail.com",
        "name": "Debmani Saha",
        "Student ID ": "PhD/22015/1027",
        "email": "debmani_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Oishila Bandyopadhyay",
        "research_area": "Image Analysis",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular ( Visvesvaraya Fellowship)",
        "links": "https://scholar.google.com/citations?user=_yBL9wYAAAAJ&hl=en",
        "img": "/phd/DebmaniSaha.webp"
    },
    {
        "index": 10,
        "Timestamp": 45027.525840532406,
        "second_email": "soma_phd_2018july@iiitkalyani.ac.in",
        "name": "Soma Das",
        "Student ID ": "PhD/CSE/18006/305",
        "email": "soma_phd_2018july@iiitkalyani.ac.in",
        "session": "2018",
        "supervisor": "Dr. Sanjoy Chatterji",
        "research_area": "Natural Language Processing",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "IEM",
        "fellowship": "",
        "links": "https://orcid.org/0000-0003-2569-2886?lang=en",
        "img": "/phd/SomaDas.webp"
    },
    {
        "index": 11,
        "Timestamp": 45027.54771719908,
        "second_email": "sayande200@gmail.com",
        "name": "Sayan De",
        "Student ID ": "PhD/22012/1024",
        "email": "sayan_jrf22@iiitkalyani.ac.in",
        "session": "2023",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Natural Language Processing",
        "pub_details": ["Agricultural Image Augmentation with Generative Adversarial Networks GANs, 2022"],
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://scholar.google.com/citations?user=zY8ENr8AAAAJ&hl=en",
        "img": "/phd/SayanDe.webp"
    },
    {
        "index": 12,
        "Timestamp": 45027.552425856484,
        "second_email": "arijit_jrf22@iiitkalyani.ac.in",
        "name": "Arijit Das",
        "Student ID ": "Phd/22001/848",
        "email": "arijit_jrf22 AT iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Oishila Bandyopadhyay, Dr. Dalia Nandi",
        "research_area": "Computer Vision",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://orcid.org/0009-0007-9507-1192",
        "img": "/phd/ArijitDas.webp"
    },
    {
        "index": 13,
        "Timestamp": 45027.55251304398,
        "second_email": "pooja_phd@iiitkalyani.ac.in",
        "name": "Pooja Rai",
        "Student ID ": "PhD/R/CSE/18020/424",
        "email": "pooja_phd@iiitkalyani.ac.in",
        "session": "2019 Spring",
        "supervisor": "Dr. Sanjay Chatterji",
        "research_area": "Natural Language Processing",
        "pub_details": ["Annotation Projection-based Dependency Parser Development for Nepali", "Feature Selection for Nepali Part-Of-Speech Tagging in a Conditional Random Fields based System"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "New Alipore College, University of Calcutta",
        "fellowship": "",
        "links": "https://www.researchgate.net/profile/Pooja-Rai-8",
        "img": "/phd/poojarai.webp"
    },
    {
        "index": 14,
        "Timestamp": 45027.55411619213,
        "second_email": "sayantan_phd20@iiitkalyani.ac.in",
        "name": "Sayantan Chatterjee",
        "Student ID ": "PhD/CSE/19014/516",
        "email": "sayantan_phd20 AT iiitkalyani.ac.in",
        "session": "Spring 2019-2020",
        "supervisor": "Dr. Bhaskar Biswas",
        "research_area": "Cryptology",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "img": "/phd/SayantanChatterjee.webp"
    },
    {
        "index": 15,
        "Timestamp": 45027.563266296296,
        "second_email": "soumenbajpayee@gmail.com",
        "name": "Soumen Bajpayee",
        "Student ID ": "PhD/21014/820",
        "email": "soumen_phd22[AT]iiitkalyani.ac.in",
        "session": "Spring 2022",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Quantum Computing and Cryptography",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://www.linkedin.com/in/soumen-bajpayee-96a02a119",
        "img": "/phd/SoumenBajpayee.webp"
    },
    {
        "index": 16,
        "Timestamp": 45027.569493703704,
        "second_email": "soumen_phd22@iiitkalyani.ac.in",
        "name": "Soumen Bajpayee",
        "Student ID ": "PhD/21014/820",
        "email": "soumen_phd22 AT iiitkalyani.ac.in",
        "session": "Spring 2022",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Quantum Computing, Cryptography",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://www.linkedin.com/in/soumen-bajpayee-96a02a119",
        "img": "/phd/SoumenBajpayee.webp"
    },
    {
        "index": 17,
        "Timestamp": 45027.570016412035,
        "second_email": "atashi_phd22@iiitkalyani.ac.in",
        "name": "Atashi Saha",
        "Student ID ": "PhD/22002/849",
        "email": "atashi_phd22 AT iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. Sanjoy Pratihar",
        "research_area": "Image Understanding, Computer Vision",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Institute Teaching Assistantship)",
        "links": "https://www.linkedin.com/itashi-saha-52237a216/",
        "img": "/phd/AtashiSaha.webp"
    },
    {
        "index": 18,
        "Timestamp": 45027.57591503472,
        "second_email": "sreeparna_phd21iii@iiitkalyani.ac.in",
        "name": "Sreeparna Ganguly",
        "Student ID ": "PhD/CSE/20009/632",
        "email": "sreeparna_phd21 AT iiitkalyani.ac.in",
        "session": "Spring 2021",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Steganalysis, Steganography, Information Security",
        "pub_details": ["Image Sterilization through Adaptive Noise Blending in Integer Wavelet Transformation"],
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Net Fellowship)",
        "links": "https://scholar.google.com/citations?user=qWTTEJ4AAAAJ&hl=en",
        "img": "/phd/SREEPARNAGANGULY.webp"
    },
    {
        "index": 19,
        "Timestamp": 45027.58194496528,
        "second_email": "shaon.bandyopadhyay@gmail.com",
        "name": "Shaon Bandyopadhyay",
        "Student ID ": "PhD/22005/852",
        "email": "shaon_phd22@iiitkalyani.ac.in",
        "session": 2022,
        "supervisor": "Dr. Sanjay pratihar",
        "research_area": "Computer Vision",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "NSEC",
        "fellowship": "",
        "links": "",
        "img": "/phd/ShaonBandyopadhyay.webp"
    },
    {
        "index": 20,
        "Timestamp": 45027.58509086806,
        "second_email": "sourabh_jrf2021@iiitkalyani.ac.in",
        "name": "Sourabh Biswas",
        "Student ID ": "PhD/22006/853",
        "email": "sourabh_jrf2021@iiitkalyani.ac.in",
        "session": "2022- 2023",
        "supervisor": "Dr. Bhaskar Biswas",
        "research_area": "Code Based Cryptography",
        "pub_details": ["Security Analysis of LDPC Code-Based Encryption"],
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://orcid.org/0009-0005-2351-8296",
        "img": "/phd/SourabhBiswas.webp"
    },
    {
        "index": 21,
        "Timestamp": 45027.58805672453,
        "second_email": "banabhi2021@gmail.com",
        "name": "Abhisek Banerjee",
        "Student ID ": "Phd-21001/649",
        "email": "abhisekb_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Cyber Security",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "IBM India Pvt Ltd",
        "fellowship": "",
        "links": "https://orcid.org/0000-0003-0247-7200",
        "img": "/phd/ABHISEKBANERJEE.webp"
    },
    {
        "index": 23,
        "Timestamp": 45027.60517097222,
        "second_email": "rp.ritesh99@gmail.com",
        "name": "Ritesh Prasad",
        "Student ID ": "PhD/21005/653",
        "email": "ritesh_phd21 AT iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Uma Das",
        "research_area": "Machine Learning, Deep Learning, Climate Data Analysis",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Brainware University",
        "fellowship": "",
        "links": "https://orcid.org/0009-0003-0522-2016",
        "img": "/phd/RITESHPRASAD.webp"
    },
    {
        "index": 24,
        "Timestamp": 45027.61040984954,
        "second_email": "soumyajit_phd21@iiitkalyani.ac.in",
        "name": "Soumyajit Pal",
        "Student ID ": "PhD/21009/657",
        "email": "soumyajit_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Uma Das, Dr. Oishila Bandyopadhyay",
        "research_area": "Machine Learning in Atmospheric Science",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "St. Xavier's College (Autonomous), Kolkata",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?hl=en&authuser=1&user=GF-2Z18AAAAJ",
        "img": "/phd/SOUMYAJITPAL.webp"
    },
    {
        "index": 25,
        "Timestamp": 45027.62085748842,
        "second_email": "abhishekmukh@iiitkalyani.ac.in",
        "name": "Abhishek Mukhopadhyay",
        "Student ID ": "PhD/R/CSE/18001/0000300",
        "email": "amukhopadhyay@iiitkalyani.ac.in",
        "session": "July, 2018",
        "supervisor": "Dr. Imon Mukherjee, Prof. Pradipta Biswas",
        "research_area": "Object Detection, Computer Vision, Man Machine Interaction",
        "status": "Ongoing",
        "type": "External",
        "Mention your Institute (For External students only)": "Indian Institute of Science",
        "fellowship": "",
        "links": "https://sites.google.com/view/amukhopadhyay/home",
        "img": "/phd/AbhishekMukhopadhyay.webp"
    },
    {
        "index": 26,
        "Timestamp": 45027.62213440972,
        "second_email": "paulsubhajit.ece@gmail.com",
        "name": "Subhajit Paul",
        "Student ID ": "PhD/22013/1025",
        "email": "subhajit_phd22@iiitkalyani.ac.in",
        "session": "2022-23",
        "supervisor": "Dr. Amit Ranjan Azad, Dr. Dalia Nandi",
        "research_area": "Microwave And Antenna Engineering",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular ( Visvesvaraya Fellowship)",
        "links": "https://scholar.google.com/citations?hl=en&user=Jzr9P9IAAAAJ",
        "img": "/phd/SubhajitPaul.webp"
    },
    {
        "index": 27,
        "Timestamp": 45027.63988935185,
        "second_email": "sayan_jrf22@iiitkalyani.ac.in",
        "name": "Sayan De",
        "Student ID ": "PhD/22012/1024",
        "email": "sayan_jrf22 AT iiitkalyani.ac.in",
        "session": "Spring Session, 2023",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Natural Language Processing",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://scholar.google.com/citations?user=zY8ENr8AAAAJ&hl=en",
        "img": "/phd/SayanDe.webp"
    },
    {
        "index": 28,
        "Timestamp": 45027.64436770833,
        "second_email": "sarbanis.sen@gmail.com",
        "name": "Sarbani Sen",
        "Student ID ": "PhD/22016/1028",
        "email": "sarbani_phd22@iiitkalyani.ac.in",
        "session": "Spring Session- 2023",
        "supervisor": "Dr. Imon Mukherjee, Dr. Uma Das",
        "research_area": "Quantum Computing and Cryptography",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "img": "/phd/SarbaniSen.webp"
    },
    {
        "index": 29,
        "Timestamp": 45027.69986363426,
        "second_email": "subhendumathsbhu@gmail.com",
        "name": "Subhendu Mandal",
        "Student ID ": "Ph.D /21012/660",
        "email": "subhendu_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Anirban Lakshman",
        "research_area": "Mathematical Modeling",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Net Fellowship)",
        "links": "https://www.researchgate.net/profile/Subhendu-Mandal-3",
        "img": "/phd/SubhenduMandal.webp"
    },
    {
        "index": 30,
        "Timestamp": 45027.711789594905,
        "second_email": "shubhasrir4@gmail.com",
        "name": "Shubhasri Roy",
        "Student ID ": "PhD/CSE/20008/631",
        "email": "shubhasri_phd21@iiitkalyani.ac.in",
        "session": "5th Session",
        "supervisor": "Dr. Debasish Bera",
        "research_area": "Blockchain",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "Institute of Engineering and Management",
        "fellowship": "",
        "links": "",
        "img": "/phd/SHUBHASRIROY.webp"
    },
    {
        "index": 31,
        "Timestamp": 45027.742693125,
        "second_email": "madhu.banik@gmail.com",
        "name": "Madhuchhanda Dasgupta",
        "Student ID ": "PhD/CSE/18018/422",
        "email": "madhuchhanda_phd19@iiitkalyani.ac.in",
        "session": "Spring 2019",
        "supervisor": "Dr. Oishila Bandyopadhyay, Dr. Sanjay Chatterji",
        "research_area": "Computer Vision, Machine Learning",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=DpzqC8UAAAAJ",
        "img": "/phd/MadhuchhandaDasgupta.webp"
    },
    {
        "index": 32,
        "Timestamp": 45027.754590729164,
        "second_email": "soumensantra.93@gmail.com",
        "name": "Soumen Santra",
        "Student ID ": "PHD/21008/656",
        "email": "soumen_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Anirban Lakshman",
        "research_area": "Mathematical Modelling",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Net Fellowship)",
        "links": "https://orcid.org/0009-0008-0667-8601",
        "img": "/phd/SOUMENSANTRA.webp"
    },
    {
        "index": 33,
        "Timestamp": 45027.808903495374,
        "second_email": "sourav_phd21@iiitkalyani.ac.in",
        "name": "Sourav Das",
        "Student ID ": "Ph.D/21010/658",
        "email": "sourav_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Sanjay Chatterji",
        "research_area": "Natural Language Processing, Topic Extraction, Language Generation",
        "pub_details": ["Probabilistic Impact Score Generation using Ktrain-BERT to Identify Hate Words from Twitter Discussions", "A Comparative Study of Sentiment Analysis and Topic Extraction Approaches during the Covid-19 Pandemic"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "NA",
        "Mention your Company/ Office (For working Part time  students only)": "Future Institute of Technology, Kolkata",
        "fellowship": "",
        "links": "https://sites.google.com/view/souravd-me/home?authuser=1",
        "img": "/phd/SOURAVDAS.webp"
    },
    {
        "index": 34,
        "Timestamp": 45027.862014756945,
        "second_email": "nayanranjan1993@gmail.com",
        "name": "Nayan Ranjan Das",
        "Student ID ": "PhD/R/ECE/18019/0000423",
        "email": "nayan_phd19@iiitkalyani.ac.in",
        "session": 2019,
        "supervisor": "Dr. Imon Mukherjee, Dr. Goutam Paul",
        "research_area": "Data Analytics",
        "pub_details": ["Adoption of a Ranking Based Indexing Method for the Cricket Teams", "Modified Hedonic Based Price Prediction Model for Players in IPL Auction", "Pose Recognition in Cricket using Keypoints"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Academy of Technology",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=FBp2IVcAAAAJ&hl=en&oi=ao",
        "img": "/phd/NayanRanjanDas.webp"
    },
    {
        "index": 35,
        "Timestamp": 45027.88787303241,
        "second_email": "bavrabi_phd21@iiitkalyani.ac.in",
        "name": "Bavrabi Ghosh",
        "Student ID ": "PhD/CSE/20002",
        "email": "bavrabi_phd21 AT iiitkalyani.ac.in",
        "session": "5th Semester (3rd year)",
        "supervisor": "Dr. Oishila Bandyopadhyay",
        "research_area": "Study of script using image analysis",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Institute of Engineering & Management",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=O572VK8AAAAJ&hl=en&oi=ao",
        "img": "/phd/BAVRABIGHOSH.webp"
    },
    {
        "index": 36,
        "Timestamp": 45027.896492141204,
        "second_email": "sudeep.ghosh123@gmail.com",
        "name": "Sudeep Ghosh",
        "Student ID ": "Phd/CSE/19008/510",
        "email": "sudeeep_phd2019@iiitkalyani.ac.in",
        "session": "Spring, 2019",
        "supervisor": "Dr. SK Hafizul Islam",
        "research_area": "Cryptography",
        "pub_details": ["Provably Secure Public Key Encryption with Keyword Search for Data Outsourcing in Cloud Environments"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Guru Nanak Institute of Technology",
        "fellowship": "",
        "links": "https://orcid.org/0000-0003-1699-1390",
        "img": "/phd/SudeepGhosh.webp"
    },
    {
        "index": 37,
        "Timestamp": 45027.91147537037,
        "second_email": "swagatam_phd2019@iiitkalyani.ac.in",
        "name": "Swagatam Basu",
        "Student ID ": "PhD/CSE/19009/0000511",
        "email": "swagatam_phd2019@iiitkalyani.ac.in",
        "session": "Spring 2019",
        "supervisor": "Dr. SK Hafizul Islam",
        "research_area": "Design and Analysis of Lattice-Based Cryptographic Protocols for Post-Quantum Environments",
        "pub_details": ["PB-3PAKA: Password-Based Three-Party Authenticated Key Agreement Protocol for Mobile Devices In Post-Quantum Environments"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "NA",
        "Mention your Company/ Office (For working Part time  students only)": "Institute of Engineering and Management, Kolkata",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=ryUB9fMAAAAJ&hl=en&oi=ao",
        "img": "/phd/SwagatamBasu.webp"
    },
    {
        "index": 38,
        "Timestamp": 45027.91325405093,
        "second_email": "sug9am@gmail.com",
        "name": "Sugam Kumar Bhunia",
        "Student ID ": "Ph.D/CSE/18023/0000427",
        "email": "sugam_phd19@iiitkalyani.ac.in",
        "session": "Spring, 2019",
        "supervisor": "Imon Mukherjee, Sambit Bakshi",
        "research_area": "Person Re-Identification",
        "pub_details": ["Utilizing Attention Mechanism with Exemplar Memory for Improving Domain Adaptive Person Re-identification"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "fellowship": "",
        "links": "0000-0001-6924-1847",
        "img": "/phd/SugamKumarBhunia.webp"
    },
    {
        "index": 39,
        "Timestamp": 45027.93617221065,
        "second_email": "sourav.uit@gmail.com",
        "name": "Sourav Samanta",
        "Student ID ": "PHD/CSE/18021/425",
        "email": "sourav_phd19@iiitkalyani.ac.in",
        "session": "Spring, 2022-23",
        "supervisor": "Dr. Sanjoy Pratihar, Dr. Sanjay Chatterji ",
        "research_area": "Application of computer vision in agriculture",
        "pub_details": ["Fast and Robust Monitoring of Broken Rice Kernels in the Course of Milling", "Leaf Spot Disease Severity Measurement in Terminalia Arjuna using Optimized Superpixels"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "University Institute of Technology, The University of Burdwan",
        "fellowship": "",
        "links": "https://orcid.org/0000-0003-0813-3919",
        "img": "/phd/SouravSamanta.webp"
    },
    {
        "index": 40,
        "Timestamp": 45027.95601070602,
        "second_email": "shiplu_phd21@iiitkalyani.ac.in",
        "name": "Shiplu Das",
        "Student ID ": "PhD/CSE/20007/630",
        "email": "shiplu_phd21@iiitkalyani.ac.in",
        "session": 2021,
        "supervisor": "Dr. Sanjoy Pratihar",
        "research_area": "Computer Vision and Deep Learning",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "fellowship": "",
        "links": "NA",
        "img": "https://drive.google.com/open?id=1FX0F-6BoYVKRzEbqh8lAj7Gs0iJDJKOS"
    },
    {
        "index": 41,
        "Timestamp": 45027.95875710648,
        "second_email": "sharmistha_phd.math19@iiitkalyani.ac.in",
        "name": "Sharmistha Rakshit",
        "Student ID ": "PhD/Sc./19006/508",
        "email": "sharmistha_phd.math19@iiitkalyani.ac.in",
        "session": "2020-2025",
        "supervisor": "Dr. Anirban Lakshman",
        "research_area": "Solid mechanics, Thermoelasticity",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://orcid.org/0000-0002-0457-578X",
        "img": "/phd/SharmisthaRakshit.webp"
    },
    {
        "index": 42,
        "Timestamp": 45027.96111751157,
        "second_email": "srinivasa_phd21@iiitkalyani.ac.in",
        "name": "Srinivasa Rao Yandrapu",
        "Student ID ": "PhD/21011/659",
        "email": "srinivasa_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Debasish Bera",
        "research_area": "Very Large Scale Integration",
        "status": "Ongoing",
        "type": "External",
        "Mention your Institute (For External students only)": "MallaReddy Engineering College for Women",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=J1-evCMAAAAJ&hl=en",
        "img": "/phd/SRINIVASARAOYANDRAPU.webp"
    },
    {
        "index": 43,
        "Timestamp": 45027.97940480324,
        "second_email": "suparna.karmakar@gnit.ac.in",
        "name": "Suparna Karmakar",
        "Student ID ": "PhD/CSE/18009/308",
        "email": "suparna_phd_2018july@iiitkalyani.ac.in",
        "session": "2018-2019",
        "supervisor": "Dr. Uma Das, Dr. Oishila Bandyopadhyay",
        "research_area": "Data Analytics",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "GURU NANAK INSTITUTE OF TECHNOLOGY, KOLKATA",
        "fellowship": "",
        "links": "https://orcid.org/0000-0001-5755-6753",
        "img": "/phd/SuparnaKarmakar.webp"
    },
    {
        "index": 44,
        "Timestamp": 45028.018531724534,
        "second_email": "chiranjit.pal.3.19@gmai.com",
        "name": "Chiranjit Pal",
        "Student ID ": "PHD/CSE/20004/627",
        "email": "chiranjit_jrf21 AT iiitkalyani.ac.in",
        "session": "2021-202",
        "supervisor": "Dr. Imon Mukherjee, Dr. Sanjoy Pratihar, Dr. Sanjay Chatterji",
        "research_area": "Image processing, Computer Vison, Deep Learning",
        "pub_details": ["Automatic Rice Crop Extraction using Edge based Color Features and Color Indices", "A custom CNN model for detection of rice disease under complex environment", "Comparative Study on Various CNNs for Classification and Identification of Biotic stress of paddy Leaf"],
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "links": "https://orcid.org/0000-0002-6852-9272",
        "img": "/phd/ChiranjitPal.webp"
        
    },
    {
        "index": 45,
        "Timestamp": 45028.10963269676,
        "second_email": "choudhury.am2011@gmail.com",
        "name": "Alokeparna Choudhury",
        "Student ID ": "PhD/CSE/18013/417",
        "email": "alokeparna_phd19@iiitkalyani.ac.in",
        "session": "2021-2028, 2nd Year",
        "supervisor": "Dr. Sanjoy Pratihar, Dr. Oishila Bandyopadhyay",
        "research_area": "Medical Image Segmentation",
        "pub_details": ["Multilevel Image Segmentation using Global Steered Quantum Inspired Firefly Algorithm", "Segmentation of Brain MR Images Using Quantum Inspired Firefly Algorithm with Mutation"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "St. Xavier's College, Burdwan",
        "fellowship": "",
        "links": "https://orcid.org/0000-0001-5998-8621",
        "img": "/phd/AlokeparnaChoudhury.webp"
    },
    {
        "index": 46,
        "Timestamp": 45028.39992707176,
        "second_email": "susovan.1985@gmail.com",
        "name": "Susovan Mondal",
        "Student ID ": "PhD/ECE/19016518",
        "email": "susovan_phd20@iiitkalyani.ac.in",
        "session": "2019-2020 (Even Semester)",
        "supervisor": "Dr. Dalia Nandi",
        "research_area": "5G, V2X(Vehicle-to-Everything)",
        "pub_details": ["Study of Path Loss Models in V2V mm-Wave Communication", "Link Level Performance Analysis of NOMA in 5G", "V2X Communication Test Bed for Smart Electrical Vehicle with 5G IOV Technology"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Behala College",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=KdTebhoAAAAJ&hl=en&oi=sra",
        "img": "/phd/SusovanMondal.webp"
    },
    {
        "index": 47,
        "Timestamp": 45028.46324943287,
        "second_email": "sayantan_phd20@iiitkalyani.ac.in",
        "name": "Sayantan Chatterjee",
        "Student ID ": "PhD/CSE/19014/516",
        "email": "sayantan_phd20 AT iiitkalyani.ac.in",
        "session": "Spring 2019-2020",
        "supervisor": "Dr. Bhaskar Biswas",
        "research_area": "Code Based Cryptology",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular (Project Staff)",
        "img": "/phd/SayantanChatterjee.webp"
    },
    {
        "index": 48,
        "Timestamp": 45028.60226814815,
        "second_email": "saha.abhisek@gmail.com",
        "name": "Abhisek Saha",
        "Student ID ": "PhD/CSE/20001/624",
        "email": "abhisek_phd21@iiitkalyani.ac.in",
        "session": "Even Semester, 2021",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Artificial Intelligence in Agriculture",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Assistant Prfessor,CSBS, Netaji Subhash Engineering College",
        "fellowship": "",
        "links": "https://orcid.org/0000-0002-0452-4472",
        "img": "/phd/ABHISEKSAHA.webp"
    },
    {
        "index": 49,
        "Timestamp": 45028.66079768518,
        "second_email": "krishnendu_phd21@iiitkaltani.ac.in",
        "name": "krishnendu Choudhury ",
        "Student ID ": "Phd/ECE/20005/628",
        "email": "krishnendu_phd21@iiitkalyani.ac.in",
        "session": "Spring 2021",
        "supervisor": "Dr. Dalia Nandi",
        "research_area": "Internet of things ",
        "pub_details": ["Detection and Prioritization of Emergency Vehicles in Intelligent Traffic Management System"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Nehru Science center ",
        "fellowship": "",
        "links": "krishnendu814u",
        "img": "/phd/KRISHNENDUCHOUDHURY.webp"
    },
    {
        "index": 50,
        "Timestamp": 45028.71175351852,
        "second_email": "smandal1983@gmail.com",
        "name": "Sourav Chandra Mandal",
        "Student ID ": "PhD/R/CSE/18007/0306",
        "email": "sourav_phd_2018july@iiitkalyani.ac.in",
        "session": "2018-2024",
        "supervisor": "Dr. Oishila Bandyopadhyay,  Dr. Sanjoy Pratihar",
        "research_area": "Medical Image Processing",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "NA",
        "Mention your Company/ Office (For working Part time  students only)": "S.N. Bose Govt. Polytechnic, Malda",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?hl=en&user=hR31ytkAAAAJ",
        "img": "https://drive.google.com/open?id=1j_r8BTM-TQuOLzvvI-TssXUXwJ0"
    },
    {
        "index": 51,
        "Timestamp": 45028.83451918981,
        "second_email": "pramod924@gmail.com",
        "name": "Pramod Kumar",
        "Student ID ": "PhD/22004/851",
        "email": "pramod_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Dr. SK Hafizul Islam, Dr. Arup Kumar Pal",
        "research_area": "Cryptography and Information Security (Secure data communication)",
        "status": "Ongoing",
        "type": "External",
        "Mention your Institute (For External students only)": "INDIAN INSTITUTE OF TECHNOLOGY (INDIAN SCHOOL OF MINES) DHANBAD.",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?hl=en&user=GYjJZe9MvpUC",
        "img": "/phd/PramodKumar.webp"
    },
    {
        "index": 52,
        "Timestamp": 45028.87638959491,
        "second_email": "sagarikaghosh.wbut2010@gmail.com",
        "name": "Sagarika Ghosh",
        "Student ID ": "PhD/R/CSE/18005/304",
        "email": "sagarika_phd_2018july@iiitkalyani.ac.in",
        "session": "2018",
        "supervisor": "Dr. Sanjay Chatterji, Dr. Sanjoy Pratihar",
        "research_area": "NLP with deep learning",
        "pub_details": ["Matching of hand-drawn flowchart, pseudocode, and english description using transfer learning"],
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Institute (For External students only)": "NA",
        "Mention your Company/ Office (For working Part time  students only)": "University of Engineering and Management Jaipur",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=xyIo4dkAAAAJ&hl=en",
        "img": "/phd/SagarikaGhosh.webp"
    },
    {
        "index": 53,
        "Timestamp": 45029.63565494213,
        "second_email": "biswajit_phd22@iiitkalyani.ac.in",
        "name": "Biswajit Halder",
        "Student ID ": "PhD/21013/819",
        "email": "biswajit_phd22@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Bhaskar Biswas",
        "research_area": "Cryptology",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "ISI Kolkata",
        "fellowship": "",
        "links": "",
        "img": "/phd/biswajit.webp"
    },
    {
        "index": 54,
        "Timestamp": 45029.66727913194,
        "second_email": "ranjan_phd20@iiitkalyani.ac.in",
        "name": "Ranjan Jana",
        "Student ID ": "Ph.D/CSE/19013/0000515",
        "email": "ranjan_phd20@iiitkalyani.ac.in",
        "session": "2019",
        "supervisor": "Dr. Imon Mukherjee",
        "research_area": "Biomedical Signal Processing",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "RCC Institute of Information Technology",
        "fellowship": "",
        "links": "https://orcid.org/0000-0002-1369-1264",
        "img": "/phd/RanjanJana.webp"
    },
    {
        "index": 55,
        "Timestamp": 45029.89665461806,
        "second_email": "srijita.basu202@gmail.com",
        "name": "Srijita Basu",
        "Student ID ": "Ph.D/R/CSE/18008/0000307",
        "email": "srijita_phd_2018july@iiitkalyani.ac.in",
        "session": "2018",
        "supervisor": "Dr. Debasish Bera",
        "research_area": "Cloud Computing, Blockchain Technology",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Jadavpur University ",
        "fellowship": "",
        "links": "https://scholar.google.com/citations?user=Af_IYesAAAAJ&hl=en",
        "img": "/phd/SrijitaBasu.webp"
    },
    {
        "index": 56,
        "Timestamp": 45031.930332916665,
        "second_email": "sumanta_phd21@iiitkalyani.ac.in",
        "name": "Sumanta Chakraborty",
        "Student ID ": "PhD/CSE/20011/634",
        "email": "sumanta_phd21@iiitkalyani.ac.in",
        "session": "2021",
        "supervisor": "Dr. Sk Hafizul Islam",
        "research_area": "Cryptography, Quantum Computation",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Techno International New Town",
        "fellowship": "",
        "links": "ORCID ID 0000000302609891",
        "img": "/phd/SUMANTACHAKRABORTY.webp"
    },
    {
        "index": 57,
        "Timestamp": 45032.67863038194,
        "second_email": "susmitad2k17@gmail.com",
        "name": "Susmita Das",
        "Student ID ": "PhD/R/ECE/18010/0000309",
        "email": "susmita_phd_2018july@iiitkalyani.ac.in",
        "session": "2018",
        "supervisor": "Dr. Dalia Nandi",
        "research_area": "Biomedical Engineering, Prosthetic Technology, Control System",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "Narula Institute of Technology(Assistant Professor)",
        "fellowship": "",
        "links": "https://scholar.google.co.in/citations?user=zZrjwKgAAAAJ&hl=en",
        "img": "/phd/SusmitaDas.webp"
    },
    {
        "index": 58,
        "Timestamp": 45036.67460412037,
        "second_email": "amritesu_phd22@iiitkalyani.ac.in",
        "name": "Amritesu Pal",
        "Student ID ": "PhD/22014/1026",
        "email": "amritesu_phd22@iiitkalyani.ac.in",
        "session": "2022",
        "supervisor": "Sanjay Chatterji",
        "research_area": "Natural language Processing",
        "status": "Ongoing",
        "type": "Regular",
        "fellowship": "Regular",
        "img": "/phd/AmritesuPal.webp"
    },
    {
        "index": 59,
        "Timestamp": 45036.71929420139,
        "second_email": "thandar.santanu@gmail.com",
        "name": "Santanu Thandar",
        "Student ID ": "Phd/22011/1023",
        "email": "santanu_phd22@iiitkalyani.ac.in",
        "session": "2023",
        "supervisor": "Dr. Sanjay Chatterji, Dr.Sajal Sarkar",
        "research_area": "Cybersecurity in Power System",
        "status": "Ongoing",
        "type": "Part time (On Service)",
        "Mention your Company/ Office (For working Part time  students only)": "The Durgapur Projects Ltd., Durgapur ",
        "fellowship": "",
        "links": "",
        "img": "/phd/santanuthandar.webp"
    },
]

export default data;